name: Publish documentation to Surge

on:
  workflow_dispatch:
    branches:
      - dev
      - master
  # push:
  #   branches:
  #   - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Surge Publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Instal and build
        run: |
          npm ci
          npm run docs
      - name: Deploy to surge
        uses: dswistowski/surge-sh-action@v1.0.0
        with:
          domain: ${{ secrets.surge_domain }}
          project: 'docs'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}